debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.ohmymoon.springboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: cjstkans
    driver-class-nane: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupledLogic: true




